project:
  type: default
  output-dir: .
  resources:
    - references.bib

render:
  - Assignment05.qmd
  - presentation.qmd

formats:
  html:
    theme: cosmo
    toc: false
    code-fold: true
  pdf:
    documentclass: article
    fig-cap-location: bottom
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    code-overflow: wrap
