<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emily Liu">
<meta name="dcterms.date" content="2025-10-08">

<title>World Development Indicators 2022 Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="Assignment05_files/libs/clipboard/clipboard.min.js"></script>
<script src="Assignment05_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Assignment05_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Assignment05_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Assignment05_files/libs/quarto-html/popper.min.js"></script>
<script src="Assignment05_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Assignment05_files/libs/quarto-html/anchor.min.js"></script>
<link href="Assignment05_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Assignment05_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Assignment05_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Assignment05_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Assignment05_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">World Development Indicators 2022 Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emily Liu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 8, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>This report analyzes three key indicators from the World Bank’s <em>World Development Indicators (2022)</em>: <strong>GDP per capita</strong>, <strong>life expectancy</strong>, and <strong>education expenditure</strong> (as a share of GDP).<br>
These metrics together illustrate economic performance, human development, and policy investment in education.</p>
</section>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">2. Summary Statistics</h2>
<div id="6d25ca41" class="cell" data-message="false" data-results="hide" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy&gt;=1.26.0 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six&gt;=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)
Requirement already satisfied: wbgapi in /opt/miniconda3/lib/python3.13/site-packages (1.0.12)
Requirement already satisfied: requests in /opt/miniconda3/lib/python3.13/site-packages (from wbgapi) (2.32.3)
Requirement already satisfied: PyYAML in /opt/miniconda3/lib/python3.13/site-packages (from wbgapi) (6.0.3)
Requirement already satisfied: tabulate in /opt/miniconda3/lib/python3.13/site-packages (from wbgapi) (0.9.0)
Requirement already satisfied: charset-normalizer&lt;4,&gt;=2 in /opt/miniconda3/lib/python3.13/site-packages (from requests-&gt;wbgapi) (3.3.2)
Requirement already satisfied: idna&lt;4,&gt;=2.5 in /opt/miniconda3/lib/python3.13/site-packages (from requests-&gt;wbgapi) (3.7)
Requirement already satisfied: urllib3&lt;3,&gt;=1.21.1 in /opt/miniconda3/lib/python3.13/site-packages (from requests-&gt;wbgapi) (2.3.0)
Requirement already satisfied: certifi&gt;=2017.4.17 in /opt/miniconda3/lib/python3.13/site-packages (from requests-&gt;wbgapi) (2025.4.26)
Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy in /opt/miniconda3/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: wbdata in /opt/miniconda3/lib/python3.13/site-packages (1.1.0)
Requirement already satisfied: matplotlib in /opt/miniconda3/lib/python3.13/site-packages (3.10.6)
Requirement already satisfied: seaborn in /opt/miniconda3/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: python-dateutil&gt;=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz&gt;=2020.1 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata&gt;=2022.7 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: appdirs&lt;2,&gt;=1.4 in /opt/miniconda3/lib/python3.13/site-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff&lt;3,&gt;=2.2.1 in /opt/miniconda3/lib/python3.13/site-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools&lt;6,&gt;=5.3.2 in /opt/miniconda3/lib/python3.13/site-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser&lt;2,&gt;=1.2.0 in /opt/miniconda3/lib/python3.13/site-packages (from wbdata) (1.2.2)
Requirement already satisfied: decorator&lt;6,&gt;=5.1.1 in /opt/miniconda3/lib/python3.13/site-packages (from wbdata) (5.2.1)
Requirement already satisfied: requests&lt;3,&gt;=2.0 in /opt/miniconda3/lib/python3.13/site-packages (from wbdata) (2.32.3)
Requirement already satisfied: shelved-cache&lt;0.4,&gt;=0.3.1 in /opt/miniconda3/lib/python3.13/site-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate&lt;1,&gt;=0.8.5 in /opt/miniconda3/lib/python3.13/site-packages (from wbdata) (0.9.0)
Requirement already satisfied: contourpy&gt;=1.0.1 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler&gt;=0.10 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools&gt;=4.22.0 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver&gt;=1.3.1 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging&gt;=20.0 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow&gt;=8 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing&gt;=2.3.1 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: regex&gt;=2024.9.11 in /opt/miniconda3/lib/python3.13/site-packages (from dateparser&lt;2,&gt;=1.2.0-&gt;wbdata) (2025.9.18)
Requirement already satisfied: tzlocal&gt;=0.2 in /opt/miniconda3/lib/python3.13/site-packages (from dateparser&lt;2,&gt;=1.2.0-&gt;wbdata) (5.3.1)
Requirement already satisfied: six&gt;=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil&gt;=2.8.2-&gt;pandas) (1.17.0)
Requirement already satisfied: charset-normalizer&lt;4,&gt;=2 in /opt/miniconda3/lib/python3.13/site-packages (from requests&lt;3,&gt;=2.0-&gt;wbdata) (3.3.2)
Requirement already satisfied: idna&lt;4,&gt;=2.5 in /opt/miniconda3/lib/python3.13/site-packages (from requests&lt;3,&gt;=2.0-&gt;wbdata) (3.7)
Requirement already satisfied: urllib3&lt;3,&gt;=1.21.1 in /opt/miniconda3/lib/python3.13/site-packages (from requests&lt;3,&gt;=2.0-&gt;wbdata) (2.3.0)
Requirement already satisfied: certifi&gt;=2017.4.17 in /opt/miniconda3/lib/python3.13/site-packages (from requests&lt;3,&gt;=2.0-&gt;wbdata) (2025.4.26)</code></pre>
</div>
</div>
<div id="32777fc1" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the indicators to download</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>indicators <span class="op">=</span> {</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'gdp_per_capita'</span>: <span class="st">'NY.GDP.PCAP.CD'</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'gdp_growth_rate'</span>: <span class="st">'NY.GDP.MKTP.KD.ZG'</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'inflation_rate'</span>: <span class="st">'FP.CPI.TOTL.ZG'</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'unemployment_rate'</span>: <span class="st">'SL.UEM.TOTL.ZS'</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_population'</span>: <span class="st">'SP.POP.TOTL'</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'life_expectancy'</span>: <span class="st">'SP.DYN.LE00.IN'</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'adult_literacy_rate'</span>: <span class="st">'SE.ADT.LITR.ZS'</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'income_inequality'</span>: <span class="st">'SI.POV.GINI'</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'health_expenditure_gdp_share'</span>: <span class="st">'SH.XPD.CHEX.GD.ZS'</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'measles_immunisation_rate'</span>: <span class="st">'SH.IMM.MEAS'</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'education_expenditure_gdp_share'</span>: <span class="st">'SE.XPD.TOTL.GD.ZS'</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'primary_school_enrolment_rate'</span>: <span class="st">'SE.PRM.ENRR'</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'exports_gdp_share'</span>: <span class="st">'NE.EXP.GNFS.ZS'</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the list of country codes for the "World" region</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>country_codes <span class="op">=</span> wb.region.members(<span class="st">'WLD'</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Download data for countries only in 2022</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> wb.data.DataFrame(indicators.values(), economy<span class="op">=</span>country_codes, time<span class="op">=</span><span class="dv">2022</span>, skipBlanks<span class="op">=</span><span class="va">True</span>, labels<span class="op">=</span><span class="va">True</span>).reset_index()</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Delete the 'economy' column</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(columns<span class="op">=</span>[<span class="st">'economy'</span>], errors<span class="op">=</span><span class="st">'ignore'</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a reversed dictionary mapping indicator codes to names</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the columns and convert all names to lowercase</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>df.rename(columns<span class="op">=</span><span class="kw">lambda</span> x: {v: k <span class="cf">for</span> k, v <span class="kw">in</span> indicators.items()}.get(x, x).lower(), inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort 'country' in ascending order</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.sort_values(<span class="st">'country'</span>, ascending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset the index after sorting</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the number of rows and columns</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows of the data</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head(<span class="dv">3</span>))</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the data to a CSV file</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>df.to_csv(<span class="st">'wdi.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(217, 14)
       country  inflation_rate  exports_gdp_share  gdp_growth_rate  \
0  Afghanistan       13.712102          18.380042        -6.240172   
1      Albania        6.725203          37.197082         4.826696   
2      Algeria        9.265516          30.808979         3.600000   

   gdp_per_capita  adult_literacy_rate  primary_school_enrolment_rate  \
0      357.261153                  NaN                            NaN   
1     6846.426694                  NaN                      96.371230   
2     4961.552577                  NaN                     105.747154   

   education_expenditure_gdp_share  measles_immunisation_rate  \
0                              NaN                       56.0   
1                         2.729770                       86.0   
2                         4.749247                       79.0   

   health_expenditure_gdp_share  income_inequality  unemployment_rate  \
0                     23.088169                NaN             14.100   
1                      6.193681                NaN             10.137   
2                      3.623043                NaN             12.346   

   life_expectancy  total_population  
0           65.617        40578842.0  
1           78.769         2777689.0  
2           76.129        45477389.0  </code></pre>
</div>
</div>
<div id="f191629d" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for three indicators</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">'gdp_per_capita'</span>, <span class="st">'life_expectancy'</span>, <span class="st">'education_expenditure_gdp_share'</span>]].describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">gdp_per_capita</th>
<th data-quarto-table-cell-role="th">life_expectancy</th>
<th data-quarto-table-cell-role="th">education_expenditure_gdp_share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">count</th>
<td>208.000000</td>
<td>217.000000</td>
<td>163.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean</th>
<td>21175.312219</td>
<td>73.108020</td>
<td>4.259828</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">std</th>
<td>31035.961639</td>
<td>7.942539</td>
<td>2.086851</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">min</th>
<td>250.634225</td>
<td>18.818000</td>
<td>0.000007</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">25%</th>
<td>2692.573957</td>
<td>67.788000</td>
<td>2.903584</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">50%</th>
<td>7713.094217</td>
<td>74.160976</td>
<td>4.054028</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75%</th>
<td>28905.928012</td>
<td>78.531000</td>
<td>5.236966</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>226052.001905</td>
<td>85.746000</td>
<td>14.786031</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<ul>
<li><p>GDP per capita ranges from approximately USD 251 to USD 226,052, with a mean of around USD 21,175 and a standard deviation exceeding USD 31,000. This wide variation indicates substantial inequality in economic output across countries.</p></li>
<li><p>Life expectancy spans from as low as 18.8 years to 85.7 years, averaging 73.1 years. The interquartile range (IQR approximately equals to 11 years) suggests that most nations fall within a relatively consistent life span range, though a few outliers pull the minimum downward.</p></li>
<li><p>Education expenditure (% of GDP) averages 4.26%, with values ranging from nearly 0% to 14.8%. This reflects large differences in how much nations allocate toward education, influenced by policy priorities, income levels, and demographic pressures.</p></li>
</ul>
</section>
<section id="visual-analysis" class="level2">
<h2 class="anchored" data-anchor-id="visual-analysis">3. Visual Analysis</h2>
<p><strong>3.1 GDP and Life Expectancy</strong></p>
<div id="cell-fig-gdp-life" class="cell" data-fig-height="6" data-fig-width="8" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-gdp-life" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" data-fig-env="figure">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gdp-life-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Assignment05_files/figure-html/fig-gdp-life-output-1.png" data-fig-env="figure" data-fig-pos="H" width="758" height="564" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gdp-life-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Relationship between GDP per Capita and Life Expectancy (2022). Source: World Development Indicators, World Bank.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Figure 1 Interpretation</strong>: The scatter plot displays a strong positive correlation between GDP per capita and life expectancy across countries in 2022. As national income rises, citizens tend to live longer — reflecting improved access to healthcare, nutrition, and living standards. However, the curve flattens for high-income nations, suggesting diminishing marginal health benefits of additional income once a country achieves a certain level of economic development.</p>
<p><strong>3.2 Education Expenditure by Country</strong></p>
<div id="cell-fig-edu-top10" class="cell" data-fig-height="6" data-fig-width="8" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-edu-top10" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-edu-top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Assignment05_files/figure-html/fig-edu-top10-output-1.png" width="758" height="566" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-edu-top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Top 10 Countries by Education Expenditure as a Percentage of GDP (2022). Source: World Development Indicators, World Bank.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Figure 2 interpretation</strong>: The bar chart highlights the ten countries investing the largest share of their GDP in education in 2022. Small island nations such as Kiribati, Tuvalu, and Vanuatu lead the list, each allocating over 10% of their GDP to education — far above the global average of approximately 4%. This trend reflects the significant emphasis these nations place on human capital development despite their limited economic scale. Larger economies like Sweden and Cuba also appear on the list, demonstrating that both developed and developing countries can prioritize education depending on their policy objectives.</p>
<div class="cell" data-execution_count="6">
<div id="tbl-summary-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary Statistics for Key Development Indicators (2022).
</figcaption>
<div aria-describedby="tbl-summary-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">gdp_per_capita</th>
<th data-quarto-table-cell-role="th">life_expectancy</th>
<th data-quarto-table-cell-role="th">education_expenditure_gdp_share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">count</th>
<td>208.00</td>
<td>217.00</td>
<td>163.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean</th>
<td>21175.31</td>
<td>73.11</td>
<td>4.26</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">std</th>
<td>31035.96</td>
<td>7.94</td>
<td>2.09</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">min</th>
<td>250.63</td>
<td>18.82</td>
<td>0.00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">25%</th>
<td>2692.57</td>
<td>67.79</td>
<td>2.90</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">50%</th>
<td>7713.09</td>
<td>74.16</td>
<td>4.05</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75%</th>
<td>28905.93</td>
<td>78.53</td>
<td>5.24</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>226052.00</td>
<td>85.75</td>
<td>14.79</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">4. Discussion</h2>
<p>As shown in <a href="#fig-gdp-life" class="quarto-xref">Figure&nbsp;1</a>, countries with higher GDP per capita generally exhibit longer life expectancy. This relationship reflects how income levels correlate with access to healthcare, nutrition, and living standards.</p>
<p>Meanwhile, <a href="#fig-edu-top10" class="quarto-xref">Figure&nbsp;2</a> highlights that several small island nations allocate more than 10% of their GDP to education — a significantly higher share compared to the global average of 4%.</p>
<p>Finally, summary statistics presented in <a href="#tbl-summary-stats" class="quarto-xref">Table&nbsp;1</a> provide an overview of global variation across GDP, life expectancy, and education expenditure, illustrating wide economic disparities.</p>
<p>According to the World Bank <span class="citation" data-cites="worldbank2022">(<a href="#ref-worldbank2022" role="doc-biblioref">Bank 2022</a>)</span>, GDP per capita remains a central indicator of economic development. Similarly, UNESCO data <span class="citation" data-cites="unesco2023">(<a href="#ref-unesco2023" role="doc-biblioref">Statistics 2023</a>)</span> highlight that education spending varies widely by region and income level.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-worldbank2022" class="csl-entry" role="listitem">
Bank, World. 2022. <span>“World Development Indicators Database.”</span> <a href="https://databank.worldbank.org/source/world-development-indicators" class="uri">https://databank.worldbank.org/source/world-development-indicators</a>.
</div>
<div id="ref-unesco2023" class="csl-entry" role="listitem">
Statistics, UNESCO Institute for. 2023. <span>“Education Expenditure as a Share of GDP, 2023 Update.”</span>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>